# Exclude specific versions from pre-commit checks
exclude: |
    (?x)(
        ^v1-0-1[3-4]/|
        ^v1-[1-4]-0/|
        ^v2-[0-2]-[0-1]/|
        ^v3-[0-2]-[0-1]/|
        ^v4-0-0/|
        ^v4-1-0/|
        ^v4-2-0/|
        ^mainsite_hidden/source_old/|
        ^mainsite_hidden/z_old_stuff/|
        ^latest/docs/_sources/11_demos/
        \.svg$|
        \.js$|
        \.js_t$|
        \.css$|
        \.js.map$|
        \.css.map$
    )

autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-byte-order-marker

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args:
          - --skip=*.ts,*.svg,*.hqx,*-inv.txt,*.iss.in,*.html,*.rst.txt  # Skip specific file types
          - --ignore-words=.codespell_ignore_words.txt

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args:
          - --py36-plus  # Upgrade syntax to Python 3.6+ compatible

  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v0.9.1
    hooks:
      - id: sphinx-lint
