var dir_747440fd67964184c75516b9c7764a8c =
[
    [ "abstractAddInConfigDialog.h", "abstract_add_in_config_dialog_8h_source.html", null ],
    [ "abstractAddInDockWidget.h", "abstract_add_in_dock_widget_8h_source.html", null ],
    [ "abstractApiWidget.h", "abstract_api_widget_8h_source.html", null ],
    [ "addInGrabber.h", "add_in_grabber_8h_source.html", null ],
    [ "addInInterface.h", "add_in_interface_8h_source.html", null ],
    [ "apiFunctionsGraphInc.h", "api_functions_graph_inc_8h_source.html", null ],
    [ "apiFunctionsInc.h", "api_functions_inc_8h_source.html", null ],
    [ "byteArray.h", "byte_array_8h_source.html", null ],
    [ "color.h", "color_8h_source.html", null ],
    [ "commonGlobal.h", "common_global_8h_source.html", null ],
    [ "commonVersion.h", "common_version_8h_source.html", null ],
    [ "fileUtils.h", "file_utils_8h_source.html", null ],
    [ "helperColor.h", "helper_color_8h_source.html", null ],
    [ "helperCommon.h", "helper_common_8h_source.html", null ],
    [ "interval.h", "interval_8h_source.html", null ],
    [ "itomPlotHandle.h", "itom_plot_handle_8h_source.html", null ],
    [ "numeric.h", "numeric_8h_source.html", null ],
    [ "param.h", "param_8h_source.html", null ],
    [ "paramMeta.h", "param_meta_8h_source.html", null ],
    [ "pluginThreadCtrl.h", "plugin_thread_ctrl_8h_source.html", null ],
    [ "qtMetaTypeDeclarations.h", "qt_meta_type_declarations_8h_source.html", null ],
    [ "retVal.h", "ret_val_8h_source.html", null ],
    [ "shape.h", "shape_8h_source.html", null ],
    [ "shapeDObject.h", "shape_d_object_8h_source.html", null ],
    [ "sharedFunctionsQt.h", "shared_functions_qt_8h_source.html", null ],
    [ "sharedStructures.h", "shared_structures_8h_source.html", null ],
    [ "sharedStructuresGraphics.h", "shared_structures_graphics_8h_source.html", null ],
    [ "sharedStructuresPrimitives.h", "shared_structures_primitives_8h_source.html", null ],
    [ "sharedStructuresQt.h", "shared_structures_qt_8h_source.html", null ],
    [ "typeDefs.h", "type_defs_8h_source.html", null ]
];