var dir_3d2c2fb9921ac0e687e0ebceee98b580 =
[
    [ "abstractCodeEditorWidget.h", "abstract_code_editor_widget_8h_source.html", null ],
    [ "abstractDockWidget.h", "abstract_dock_widget_8h_source.html", null ],
    [ "AIManagerWidget.h", "_a_i_manager_widget_8h_source.html", null ],
    [ "bookmarkDockWidget.h", "bookmark_dock_widget_8h_source.html", null ],
    [ "breakPointDockWidget.h", "break_point_dock_widget_8h_source.html", null ],
    [ "callStackDockWidget.h", "call_stack_dock_widget_8h_source.html", null ],
    [ "consoleWidget.h", "console_widget_8h_source.html", null ],
    [ "figureWidget.h", "figure_widget_8h_source.html", null ],
    [ "fileSystemDockWidget.h", "file_system_dock_widget_8h_source.html", null ],
    [ "helpDockWidget.h", "help_dock_widget_8h_source.html", null ],
    [ "itomQWidgets.h", "itom_q_widgets_8h_source.html", null ],
    [ "lastCommandDockWidget.h", "last_command_dock_widget_8h_source.html", null ],
    [ "mainWindow.h", "main_window_8h_source.html", null ],
    [ "menuOnlyForEnter.h", "menu_only_for_enter_8h_source.html", null ],
    [ "outlineSelectorWidget.h", "outline_selector_widget_8h_source.html", null ],
    [ "pythonMessageDockWidget.h", "python_message_dock_widget_8h_source.html", null ],
    [ "scriptDockWidget.h", "script_dock_widget_8h_source.html", null ],
    [ "scriptEditorPrinter.h", "script_editor_printer_8h_source.html", null ],
    [ "scriptEditorWidget.h", "script_editor_widget_8h_source.html", null ],
    [ "shortcutAction.h", "shortcut_action_8h_source.html", null ],
    [ "tabSwitcherWidget.h", "tab_switcher_widget_8h_source.html", null ],
    [ "userManagement.h", "user_management_8h_source.html", null ],
    [ "userManagementEdit.h", "user_management_edit_8h_source.html", null ],
    [ "userUiDialog.h", "user_ui_dialog_8h_source.html", null ],
    [ "userUiWidget.h", "user_ui_widget_8h_source.html", null ],
    [ "workspaceDockWidget.h", "workspace_dock_widget_8h_source.html", null ],
    [ "workspaceWidget.h", "workspace_widget_8h_source.html", null ]
];